### ISSUE TITLE
Could you provide tags and releases

### ISSUE THREAD

**Issue by olivier-stasse** [pal-robotics/pmb2_robot#3]
Dear @v-lopez could you provide the tags and releases of your package ?

The last release indicates 0.1.0 where as the package is at version 1.1.8.

This would allow to have the tar.gz file of your package directly available from github.

Thanks a lot for your help.
Best,
Olivier.

**Comment by v-lopez** [comment]
Hi, I've tagged the latest version as 1.1.9

https://github.com/pal-robotics/pmb2_robot/commit/7aa809f9e26cb34657c9b5fcb75e5ccf0c1d4ab2

Most of the public PMB2 and TIAGo packages differ from our internal version. This is not the case with TALOS.

Later this year we'll unify these and solve these kind of issues, but for now there may be some discrepancies like the one you pointed out.

**Comment by olivier-stasse** [comment]
Dear Victor,
Thank you very much. The main reason for this is that LAAS has a packaging system relying on releases. They  are therefore a key information. Right now, for TALOS and TIAGO we plan to generate the binary for the robots using the dubnium and erbnium images that are provided by PAL. Outside the robots we prefer to rely on pure Ubuntu LTS releases.

**Comment by v-lopez** [comment]
No problem, glad we can be of help.

Just keep in mind that there might be differences on some TIAGo packages between what you can get from github and what is on the robots.

If you encounter any of these, feel free to contact us and we'll see how to fix it.
