### ISSUE TITLE
Simulation fail at start

### ISSUE THREAD

**Issue by AufarZakiev** [pal-robotics/pmb2_robot#4]
Hello,
Thank you for your work
I have trouble with simulations on PMB2 robot.
I have Ubuntu 14.04 and ROS Indigo installed. I went through this [guide](http://wiki.ros.org/Robots/PMB-2). When I start the simulation, Gazebo spawns with all the environment and robot in it. However, gazebo's node immediately dies after that and robot cannot be controlled. 

Gazebo window stay still and working: 
![screenshot from 2018-06-14 14 44 08](https://user-images.githubusercontent.com/5558521/41410227-6ff95272-6fe1-11e8-9ebe-8d8fba8ea7d0.png)

I attach the log file of the launch: [logs.txt](https://github.com/pal-robotics/pmb2_robot/files/2102144/logs.txt)

Could you help me please to solve this issue?

My thoughts: 
1) This could be caused by packages `speed_limit` and `sensor_to_cloud` absence (I could not find them on PAL Robotics' Github)
2) This simulation launches fine in Developer OS provided on USB-stick with real PMB2 robot. It is also Ubuntu 14.04 with ROS Indigo, but it has multiple problems with drivers(Wi-Fi and USB), so I wanted to be able launch simulations in common Ubuntu. Hope this helps.

Will be glad to any help

**Comment by v-lopez** [comment]
We've been able to reproduce this as well.

We have updated the rosinstall you have to use, it is now located at https://raw.githubusercontent.com/pal-robotics/pmb2_tutorials/indigo-devel/pmb2_public.rosinstall

Could you please try with this version?

**Comment by AufarZakiev** [comment]
Thank you for fast response!

1) I deleted previous version of `pmb2_public_ws` and followed the guide with new rosinstall file.
2) Then I run `catkin_make` command and it was almost successful, with errors on "ros_controllers". Catkin logs are here: 
[logs_catkin_make2.txt](https://github.com/pal-robotics/pmb2_robot/files/2105469/logs_catkin_make2.txt)
3) Despite the errors, I tried to launch the simulation. Simulation started, even the blue region of laser scanning was displayed. However, there were several errors in logs and keyboard control was not working. Gazebo logs are here: 
[logs_gazebo2.txt](https://github.com/pal-robotics/pmb2_robot/files/2105478/logs_gazebo2.txt)
4) I downloaded `ros-control` package using 
```bash
apt-get install ros-indigo-ros-control
```
5) Built the workspace again using `catkin_make`. Now it was more successful, with several errors. Catkin logs are here: 
[logs_catkin_make3.txt](https://github.com/pal-robotics/pmb2_robot/files/2105485/logs_catkin_make3.txt)
6) Launched Gazebo simulation and everything worked! Including keyboard control :) Thank you very much!

Could you help to fix build errors please?

**Comment by v-lopez** [comment]
You have to uninstall  ros-indigo-ros-control and all ROS Control related packages.

There's some kind of interaction where it will use the ROS Control packages in /opt instead of your workspace.

You can see it also happens here: https://answers.ros.org/question/292578/is-the-tutorial-to-compile-tiago-with-ros-kinetic-working/

**Comment by AufarZakiev** [comment]
Yes, this helped!
More precisely, these commands:
```bash
apt-get remove ros-indigo-ros-control
apt-get remove ros-indigo-controller-interface
```
I pasted them here, maybe it will help someone further.
Thank you very much again!
