### ISSUE TITLE
Collision model smaller than real world part

### ISSUE THREAD

**Issue by jmirabel** [pal-robotics/pmb2_robot#6]
The base model defined at the line is smaller than the real one (the diameter is about 5cm smaller).
https://github.com/pal-robotics/pmb2_robot/blob/330c54fee6f9be429447b400d45367bbbd239164/pmb2_description/urdf/base/base.urdf.xacro#L60

The correct file seems to be `meshes/base/base_collision.dae`. Fortunately, we stopped the robot early enough.

**Comment by v-lopez** [comment]
Thanks for reporting this, we're looking into it. Apologies for any inconvenience caused.

**Comment by v-lopez** [comment]
We ended up creating a new mesh for the collisions, the .dae file that was there was too low.

https://github.com/pal-robotics/pmb2_robot/commit/6f2f482804f174457056a6f1d323dbd6d1d5b2b3

Cheers

**Comment by jmirabel** [comment]
Thank you.
