### ISSUE TITLE
Laser not working in gazebo when no GPU available

### ISSUE THREAD

**Issue by fireblonde** [pal-robotics/pmb2_robot#9]
Hello,

We have found that the laser doesn't work in gazebo for the tiago simulations, and traced it back to the following change:

https://github.com/pal-robotics/pmb2_robot/blob/da3e237a7ea8cac1d798b657d447ff013a8a57a0/pmb2_description/urdf/sensors/sick_tim571_laser.gazebo.xacro#L38 to
https://github.com/pal-robotics/pmb2_robot/blob/c8ad1e336c895e2ebd23fd950a03eacf9c0110eb/pmb2_description/urdf/sensors/sick_tim571_laser.gazebo.xacro#L39

This loads the Gazebo GPU Laser Plugin which doesn't seem to work when using an non-dedicated GPU.

We also found that `export LIBGL_ALWAYS_SOFTWARE=1` (which we found in https://answers.gazebosim.org/question/9016/strange-hokuyo-laser-range-with-libgazebo_ros_gpu_laserso/?answer=12523#post-id-12523) solves the issue (although it disables all gpu rendering). It would be great if this would check for the existence of the GPU, otherwise it may be good to document that this environment variable may fix the issue.

**Comment by saikishor** [comment]
Hello @fireblonde,

Yes, the usual TIAGo simulation is based on the GPU based plugin. We have moved to the GPU based plugin as we saw that it speeds up the RT factor when loading heavy worlds. Unfortunately, it doesn't check if the GPU exists or not and act based on that. We will try to document the environmental variable fix that you mentioned. Thank you for sharing the tip.

Best Regards,
PAL Robotics Team.

**Comment by saikishor** [comment]
Hello @fireblonde!

Sorry for updating you late on this. We have already updated [our wiki page](http://wiki.ros.org/Robots/PMB-2/Tutorials) to include the tip that you recommended to us. Thank you so much
![image](https://github.com/pal-robotics/pmb2_robot/assets/10082428/f4a78cbb-ea71-4802-bf5b-f307b226e182)

Best Regards,
PAL Robotics Team
